version: "3.8"

services:
  postgres:
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_USER=n8n
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=n8n
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U n8n"]
      interval: 5s
      timeout: 5s
      retries: 10

  n8n:
    image: n8nio/n8n
    restart: always
    ports:
      - "5678:5678"
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_DATABASE=n8n
      - DB_POSTGRESDB_USER=n8n
      - DB_POSTGRESDB_PASSWORD=mysecretpassword
    depends_on:
      postgres:
        condition: service_healthy

  redis:
    image: redis:alpine
    restart: always

  # --- YENİ SERVİS ---
  metabase:
    image: metabase/metabase:latest
    restart: always
    ports:
      - "3030:3000" # React portu ile çakışmaması için burayı 3030:3000 olarak değiştirebiliriz, şimdilik böyle kalsın.
    depends_on:
      - postgres
    volumes:
      - metabase_data:/metabase-data

volumes:
  postgres_data:
  metabase_data: # Yeni volume
