services:
  postgres:
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_USER=n8n
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=n8n
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U n8n"]
      interval: 5s
      timeout: 5s
      retries: 10

  n8n:
    image: n8nio/n8n
    restart: always
    ports:
      - "5678:5678"
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_DATABASE=n8n
      - DB_POSTGRESDB_USER=n8n
      - DB_POSTGRESDB_PASSWORD=mysecretpassword
      - EXECUTIONS_DATA_SAVE_ON_SUCCESS=all
      - N8N_API_KEY=flowforge-super-secret-key-eren-1234e5
    depends_on:
      postgres:
        condition: service_healthy

  redis:
    image: redis:alpine
    restart: always

  metabase:
    image: metabase/metabase:latest
    restart: always
    ports:
      - "3030:3000"
    depends_on:
      - postgres
    volumes:
      - metabase_data:/metabase-data

volumes:
  postgres_data:
  metabase_data:
